language: node_js
node_js: 6

cache:
  directories:
  - node_modules  # NPM packages
  - bower_components  # bower packages
  - /home/travis/.nvm/versions/node/v6.5.0/lib/node_modules  # global NPM packages

install:
  - npm install -g bower polymer-cli@0.12.0
  - bower install

script: echo "Deploying!"

before_deploy: polymer build
deploy:
  - provider: firebase
    skip_cleanup: true
    on:
      tags: true
    project: devfestcz-b77a3
    token:
      secure: "sSAtLVem3quSHRIeSlnKIu9QSJ20IMKRDmKa9sZ4j0zSqo3RCB69s75eoygbT5pglSyWZLcnW+LVhftkJp6kRAKX/XIbVq1alv8Cwbpl/ZT9TFWhEkS6swPva3/5qTh9Z4zxPFD8hgy4/vYLA+rdSSN/hQR+doTJD9m6FTX3/cTG5XgRvUOTi5iY59cD8GB1a3/HYmHbRcxEhr2xZgIwPZgLPah3QCy+Djy84jEe39wt1GnTy1l41Kia9BgCZ+EeW1kU2wObqvE+rtnbhTscHGu0HD+fEKxzlTyJAKNp2zQonzh5UHOcko6i3KTWmgSI+GMTGKdo+zMheCyep0hJc9Czen2XvtlLrW/mTclyXc5h3NRzd5bRz6md+99mCxj5LxzgGetxO/ogk1vQ2ctTn1M3ZTj7YbwMi2/nso1I6xsToZQDNa/wCx/2vWl6+bsj+XiPcpiorqCFC2b2w6sEHGuxnWZaH2Ll2DNXoEokUSyxkZWl14GT7gJWayoP+nmZLE9eLI8/sJG8r8dxZMJ0iYM6jNtHuz4hHoIuYDuSuPQdu08Z/7jiF3GROkTY7tqrvYBa7Jw4kGJ54/9vX4lAlhY/dE4FSXzYfgBdkw9W0YShTQHBHGmU/F5Ogk0sYTF7/YXPIEy0kWpbXb4iFYyt3ESgz90vh/T2gobcfPRxLVQ="
